# Generated by Django 2.1.4 on 2020-02-22 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isCompleted', models.BooleanField(default=False)),
                ('dueDate', models.DateField(blank=True, default=None, null=True)),
                ('note', models.TextField(default='')),
                ('starred', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
