# Generated by Django 2.1.4 on 2020-02-22 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='dueDate',
        ),
    ]
