# Generated by Django 2.1.4 on 2020-02-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todos_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='dueDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
